config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'index#index'
  get 'title_doc', to: 'index#title_doc'

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create] do
    collection do
      delete :destroy
    end
  end

  resources :labs, only: [:show] do
    member do
      get :download
    end
  end
  resources :ciphers, only: [] do
    collection do
      post :caesars
      post :xor
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/caesar.rb
class Caesar
  attr_reader :offset

  LOW_RU_ALPHABET = Array('а'..'я')
  UP_RU_ALPHABET = Array('А'..'Я')
  LOW_EN_ALPHABET = Array('a'..'z')
  UP_EN_ALPHABET = Array('A'..'Z')

  def initialize(offset = 8)
    @offset = offset
    @encryptor = create_encryption_table(offset)
    @decryptor = create_encryption_table(-offset)
  end

  def offset=(offset)
    @offset = offset
    @encryptor = create_encryption_table(offset)
    @decryptor = create_encryption_table(-offset)
  end

  def encode(text)
    text.chars.map { |c| @encryptor.fetch(c, c) }.join
  end

  def decode(text)
    text.chars.map { |c| @decryptor.fetch(c, c) }.join
  end

  private

  def create_encryption_table(offset)
    [
      Hash[LOW_RU_ALPHABET.zip(LOW_RU_ALPHABET.rotate(offset))],
      Hash[UP_RU_ALPHABET.zip(UP_RU_ALPHABET.rotate(offset))],
      Hash[LOW_EN_ALPHABET.zip(LOW_EN_ALPHABET.rotate(offset))],
      Hash[UP_EN_ALPHABET.zip(UP_EN_ALPHABET.rotate(offset))]
    ].inject(&:merge)
  end
end

app/models/lab.rb
class Lab < ApplicationRecord
  validates :title, :topic, :goal, :task, :partial_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  MAX_ATTEMPTS = 7
  has_secure_password

  validates :name, :email, presence: true
  validates :email, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, length: { minimum: 10, maximum: 32 }, if: :password

  scope :locked, -> { where('attempts >= ?', MAX_ATTEMPTS) }

  before_save { self.email = email.downcase }

  def locked?
    attempts >= MAX_ATTEMPTS
  end
end

app/models/xor.rb
class XOR
  attr_accessor :key

  def initialize(key)
    @key = key.codepoints
  end

  def encrypt(text)
    text.codepoints.map.with_index do |c, i|
      (c ^ @key[i % @key.size]).chr
    end.join
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def set_labs
    @labs = Lab.order(created_at: :asc)
  end

  def authenticate_user!
    redirect_to new_session_path, alert: t('users.sessions.unauthenticated') unless logged_in?
  end
end

app/controllers/ciphers_controller.rb
class CiphersController < ApplicationController
  skip_before_action :verify_authenticity_token

  def caesars
    @caesar = Caesar.new(params[:offset].to_i)
    @result = params[:encode] == '1' ? @caesar.encode(params[:text]) : @caesar.decode(params[:text])
    render json: { text: @result }
  end

  def xor
    @xor = XOR.new(params[:key])
    render json: { text: @xor.encrypt(params[:text]) }
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  before_action :set_labs, except: [:title_doc]

  def index; end

  def title_doc
    send_file "#{Rails.root}/app/assets/docs/title.docx"
  end
end

app/controllers/labs_controller.rb
class LabsController < ApplicationController
  before_action :set_labs, except: :download
  before_action :set_lab
  before_action :authenticate_user!, only: :show, if: -> { @lab.partial_name.in?(%w[lab_4 lab_5]) }

  def show; end

  def download
    send_file "#{Rails.root}/app/assets/docs/#{@lab.asset_name}"
  rescue ActionController::MissingFile => exception
    logger.info "Rendering 404: #{exception.message}"
    render file: "#{Rails.root}/public/404.html", status: 404, layout: false
  end

  private

  def set_lab
    @lab = Lab.find params[:id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :set_labs, except: :destroy
  before_action :set_user, only: :create

  def new
    redirect_to root_url if logged_in?
  end

  def create
    if @user&.authenticate(params[:session][:password])
      reject_locked!
    else
      @user&.increment!(:attempts) unless @user&.locked?
      flash.now[:error] = I18n.t('users.sessions.error')
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url, notice: I18n.t('users.sessions.logout')
  end

  private

  def set_user
    @user = User.find_by email: params[:session][:email].downcase
  end

  def reject_locked!
    if @user.locked?
      redirect_to new_session_path, alert: I18n.t('users.sessions.locked')
    else
      log_in @user
      redirect_to root_url, success: I18n.t('users.sessions.success', name: @user.name)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_labs

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = I18n.t('users.registrations.success', name: @user.name)
      redirect_to new_session_path
    else
      flash.now.alert = I18n.t('users.registrations.error')
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title }
  end

  def active_class?(test_path)
    request.path == test_path ? 'active' : ''
  end

  def flash_class(level)
    case level
    when :notice then 'alert alert-info'
    when :success then 'alert alert-success'
    when :error then 'alert alert-danger'
    when :alert then 'alert alert-danger'
    end
  end

  def errors_for(model, field)
    if model.errors[field].any?
      content_tag(:div, class: 'invalid-feedback') do
        model.errors[field].first
      end
    end
  end
end

app/helpers/ciphers_helper.rb
module CiphersHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/index/index.html.haml
.row
  .col-md-4.col-sm-12
    = render 'shared/lab_list'
  .col-md-8.col-sm-12
    = render 'shared/title'

app/views/labs/labs/_lab_1.html.haml
%h5.text-center.mt-4#process= t('nav.process')
.report
  %p Нормою світовою практики є надання послуг у вигляді «аутсорсингу» та «аутстафінгу». В Україні дані послуги не на стільки поширені тому їх правове регулювання на даний момент ще недостатнє та недосконале.
  %p Законодавтсво чітко не визначає термін «аутстафінг» проте, ст. 39 ЗУ «Про зайнятість населення» передбачений такий вид діяльності, як «діяльність суб’єктів господарювання, які наймають працівників для подальшого виконання ними роботи в Україні в іншого працедавця», що є тотожним поняттю аутстафінгу. Також, п.п. 14.1.183. ПКУ містить визначення послуги з надання персоналу — господарська або цивільноправова угода, відповідно до якої особа, що надає послугу (резидент або нерезидент), направляє у розпорядження іншої особи (резидента або нерезидента) одну або декількох фізичних осіб для виконання визначених цією угодою функцій.
  %p В свою чергу визначення аутсорсингу наведено в розд. 4 Національного класифікатора України «Класифікація видів економічної діяльності» ДК 009:2010,«аутсорсинг» – угода, згідно з якою замовник доручає підряднику виконати певні завдання, зокрема, частину виробничого процесу або повний виробничий процес, надання послуг щодо підбору персоналу, допоміжні функції. Таким чином, аутсорсинг – це передача однією компанією певних бізнеспроцесів, функцій або конкретних завдань на виконання іншій компанії (аутсорсеру), що спеціалізується у відповідній галузі.
  %p
    ІТ, як відомо, досить популярний бізнес в Україні, який з кожним днем стає більш привабливим для іноземного інвестора. Не секрет, що початківці ІТ індустрії мріють про інвестора та підтримку свого проекту, який з часом можливо змінив би світ на краще.
  %p
    Присутність на ринку іноземного інвестора, який не проти працювати з талановитими спеціалістами, щоденно зростає. Пропозиція перевищує попит, а тому, в переважній більшості випадків, іноземний інвестор часто обирає дрібні та середні проекти, які уже мають певні обсяги продажів та є перспективними.
  %p
    Одним із важливих елементів безпеки Вашого ІТ бізнесу є його внутрішня структура. Окрім генерування ідей та прорахунку бізнес плану, Вам необхідно пройти ряд нескладних формальностей пов’язаних з реєстрацією діяльності. Легалізація проекту забезпечить Вам роботу в рамках правового поля. Погодьтеся, інвестор працювати з сумнівним контрагентом не наважиться. До того ж, є висока вірогідність того, що з часом, Вашою діяльністю можуть зацікавитися правоохоронні та контролюючі органи, а легальна структура та правильно оформлені відносини допоможуть уникнути негативного розвитку подій.
  %p У випадку безпосередньої участі іноземного інвестора, як правило, не створюється робочих місць, перевага надається співпраці з фізичними особами – підприємцями (ФОП). Така форма організації роботи нерезидента є досить вигідною для нього з точки зору оптимізації податкового навантаження та витрат на утримання персоналу. В цьому контексті, може розвиватися і так форма співпраці, коли один з ФОПів є project – менеджером та отримує і розпоряджається значною частиною коштів, може бути орендарем офісу та обладнання, здавати його в суборенду, тощо.
  %p За такої моделі переваги для Вас є очевидними, однак є і ризик того, що контролюючими органами дані відносини можуть трактуватися як трудові з можливістю притягнення до відповідальності за ухилення від сплати податків та приховування трудових відносин. Хоча, за умови правильного оформлення документів, такі ризики суттєво зменшуються.
  %p За варіанту аутсорсингу обов’язковим є укладення договору з нерезидентом. В подальшому українська компанія укладає відповідні договори з девелоперами. Так, замовник сплачує кошти одній компанії, а не кожному розробнику окремо. Однак, за такої форми ведення бізнесу зростуть Ваші адміністративні витрати. Крім того, на виконавців Ви не зможете поширити вимоги законодавства нерезидента, які можуть бути поширені на Вас у відповідності до умов договору. Якщо Ви є виконавцем, то така умова загалом є позитивною для Вас, адже Ви будете працювати на українську компанію в рамках національного права.
  %p У випадку, якщо Ваша компанія при укладенні договору з замовником надає послуги силами власних працівників, ризики щодо притягнення до відповідальності за ухилення від сплати податків зі сторони контролюючих органів зменшуються.
  %p Маєте врахувати те, що така модель є найбільш витратною, так як дохід найманих працівників не може бути оподаткований по спрощеній системі. Крім того, Вам, як роботодавцю, потрібно буде сплачувати обов’язкові збори та єдиний внесок на загальнообов’язкове державне соціальне страхування за кожного працівника.
  %p Також у законі України «Про основи національної безпеки України» та в «Доктрині інформаційної безпеки України» згадуються поняття про «комп’ютерна злочинність» та «комп’ютерний тероризм», проте визначення цих термінів в законі немає. В законі «Про боротьбу з тероризмом» поняття «комп’ютерний тероризм» не висвітлюється зовсім, а те що до нього відноситься називається «технологічним тероризмом». Для покращення нормативно-правової бази у сфері кіберзлочинності Верховною Радою України було розглянуто законопроекти: «Про основні засади забезпечення кібербезпеки України» (реєстр. №2126а від 19.05.2015) та «Про внесення змін до деяких законів України щодо посилення відповідальності за вчинені правопорушення у сфері інформаційної безпеки та боротьби з кібезлочинністю» (реєстр. № 2133а від 19.06.2015). В законопроекті № 2126а визначили терміни «кіберзлочинність» та «кібертероризм».
  %p 
    %strong Документація:
  %ul
    %li
      Розпорядження КМУ
      %a{href: 'http://zakon.rada.gov.ua/laws/show/247-2002-%D1%80'} 
        "Про затвердження Концепції легалізації програмного забезпечення та боротьби з нелегальним його використанням" від 15 травня 2002 р.
    %li 
      Закон України 
      %a{href: 'http://search.ligazakon.ua/l_doc2.nsf/link1/Z0334_0.html#'}
        «Про оподаткування прибутку підприємств» від 28.12.94 р. № 334/94-ВР.
    %li
      Закон України
      %a{href: 'http://search.ligazakon.ua/l_doc2.nsf/link1/Z970400.html#'}
        «Про збір на обов'язкове державне пенсійне страхування» від 26.06.97 р. № 400/97-ВР.
    %li
      Закон України
      %a{href: 'http://search.ligazakon.ua/l_doc2.nsf/link1/T001587.html#'} 
        «Про розповсюдження примірників аудіовізуальних творів, фонограм, відеограм, комп'ютерних програм, баз даних» від 23.03.2000 р. № 1587-III.
    %li
      Закон України
      %a{href: 'http://search.ligazakon.ua/l_doc2.nsf/link1/T379200.html#'}
        «Про авторське право і суміжні права» від 23.12.93 р. № 3792-XII.
    %li
      Постанова ВРУ
      %a{href: 'http://zakon.rada.gov.ua/laws/show/4538-17'}
        Про Рекомендації парламентських слухань на тему: "Створення в Україні сприятливих умов для розвитку індустрії програмного забезпечення" від 1 липня 2012р.
    %li
      Указ Президента України. 
      %a{href: 'http://zakon.rada.gov.ua/laws/show/96/2016'}
        «Про Стратегію кібербезпеки України». – Відомості Верховної Ради – 2016. – №96/2016
    %li
      Кримінальний кодекс України. Розділ ХVI «Злочини в сфері використання електронно-обчислювальних машин (комп’ютерів), систем та комп’ютерних мереж і мереж електрозв’язку» – Відомості Верховної Ради (ВВР) – 2001. – №25-26, ст. 131.
%h5.text-center.mt-4#conclusion= t('nav.conclusion')
.report
  %p Наведені в даній лабораторній роботі посилання та супроводжуючий текст чітко формують можливі складнощі, які можуть спіткати керівника аутсорсингової компанії з розробки ПЗ.
  %p В зв'язку з цим Верховною Радою, Президентом та Кабінетом Міністрів України були видані наведені нормативно-правові акти.
  %p Незважаючи на значне поширення аутсорсингу та аутстафінгу в Україні на 2018 рік їх правове врегулювання потребує значних зусиль для удосконалення.
  %p Але, керівник, який знає та розуміє наведені в ЛР акти, а також дотримується їх має певний (хоч і не ідеальний) захист з боку держави.
  %p Також для керівника повинні бути важливими відомості про оподаткування та співпрацю з працівниками, які є ФОПами. 
  %p Таким чином зібрані законодавчі та нормативні акти дозволять уникнути організаційних труднощів, фінансових та інших законодавчих санкцій у керуванні компанією з розробки ліцензованого ПЗ.

app/views/labs/labs/_lab_2.html.haml
%h5.text-center= t('nav.process')
%h5.text-center= t('nav.conclusion')

app/views/labs/labs/_lab_3.html.haml
%h5.text-center.mt-4#theory= t('nav.theory')
.report
  %p
    %strong Шифр Цезаря 
    — симетричний алгоритм шифрування підстановками. Використовувався римським імператором Юлієм Цезарем для приватного листування.
    Принцип дії полягає в тому, щоб циклічно зсунути алфавіт, а ключ — це кількість літер, на які робиться зсув.
  %p 
    Шифр Цезаря має замало ключів — на одиницю менше, ніж літер в абетці. Тому перебрати усі ключі не складає особливої роботи. Дешифрування з одним з ключів дасть нам вірний відкритий текст.
  %p
    %strong Шифр XOR
    — алгоритм шифрування, який як ключ використовує ключове слово та може бути записаний формулою
    Ci = Pi XOR Kj.
    де Kj - j-та літера ключового слова представлена в кодуванні ASCII.
    XOR — логічна та бітова операція, що приймає значення "істина" тоді і лише тоді коли значення «істина» має рівно один з її операндів.


%h5.text-center.mt-4#algorithm= t('nav.algorithm')
.report
  %p
    %strong Шифр Цезаря
    Якщо зіставити кожному символу алфавіту його порядковий номер (нумеруючи з 0), то шифрування і дешифрування можна виразити формулами:
    %br
    %img{ src: 'https://wikimedia.org/api/rest_v1/media/math/render/svg/d0340125bb9f010d55cbca5c26f9e6704da63037' }
    %br
    %img{ src: 'https://wikimedia.org/api/rest_v1/media/math/render/svg/647768d4e65a71fa84f436aeb99e5b125cfd0e81' }
    де 
    %em x
    — порядковий номер символу відкритого тексту, 
    %em y 
    — порядковий номер символу шифрованого тексту, 
    %em n — потужність алфавіту, а
    %em k
    — ключ.
  %p
    %strong Шифр XOR
    використовує ключове слово та може бути записаний формулою
    Ci = Pi XOR Kj.
    де Kj - j-та літера ключового слова представлена в кодуванні ASCII.

%h5.text-center.mt-4#listing= t('nav.listing')
%ul#pills-tab.nav.nav-pills.mb-3{:role => "tablist"}
  %li.nav-item
    %a#pills-caesar-tab.nav-link.active{"aria-controls" => "pills-caesar", "aria-selected" => "true", "data-toggle" => "pill", :href => "#pills-caesar", :role => "tab"}= t('lab3.caesars')
  %li.nav-item
    %a#pills-xor-tab.nav-link{"aria-controls" => "pills-xor", "aria-selected" => "false", "data-toggle" => "pill", :href => "#pills-xor", :role => "tab"}= t('lab3.xor')
#pills-tabContent.tab-content
  #pills-caesar.tab-pane.fade.show.active{"aria-labelledby" => "pills-caesar-tab", :role => "tabpanel"}
    %pre
      %code{class: 'ruby'}
        :preserve
          class Caesar
            attr_reader :offset

            LOW_RU_ALPHABET = Array('а'..'я')
            UP_RU_ALPHABET = Array('А'..'Я')
            LOW_EN_ALPHABET = Array('a'..'z')
            UP_EN_ALPHABET = Array('A'..'Z')

            def initialize(offset = 8)
              @offset = offset
              @encryptor = create_encryption_table(offset)
              @decryptor = create_encryption_table(-offset)
            end

            def offset=(offset)
              @offset = offset
              @encryptor = create_encryption_table(offset)
              @decryptor = create_encryption_table(-offset)
            end

            def encode(text)
              text.chars.map { |c| @encryptor.fetch(c, c) }.join
            end

            def decode(text)
              text.chars.map { |c| @decryptor.fetch(c, c) }.join
            end

            private

            def create_encryption_table(offset)
              [
                Hash[LOW_RU_ALPHABET.zip(LOW_RU_ALPHABET.rotate(offset))],
                Hash[UP_RU_ALPHABET.zip(UP_RU_ALPHABET.rotate(offset))],
                Hash[LOW_EN_ALPHABET.zip(LOW_EN_ALPHABET.rotate(offset))],
                Hash[UP_EN_ALPHABET.zip(UP_EN_ALPHABET.rotate(offset))]
              ].inject(&:merge)
            end
          end
  #pills-xor.tab-pane.fade{"aria-labelledby" => "pills-xor-tab", :role => "tabpanel"}
    %pre
      %code{class: 'ruby'}
        :preserve
          class XOR
            attr_accessor :key

            def initialize(key)
              @key = key.codepoints
            end

            def encrypt(text)
              text.codepoints.map.with_index do |c, i|
                (c ^ @key[i % @key.size]).chr
              end.join
            end
          end
%h5.text-center.mt-4#results= t('nav.results')
.report
= render 'labs/labs/lab_3/tabs'
%h5.text-center.mt-4#conclusion= t('nav.conclusion')
.report
  %p
    В даній лабораторній роботі я ознайомився з основними підходами до організації інформаційної безпеки, з основними методами шифрування інформації. Набув знань із реалізації методів шифрування інформації у вигляді програмних модулів.
  %p
    Освоїв основні методи шифрування інформації, на прикладі алгоритму шифрів Цезаря та XOR, сформував структуру та реалізував модулі шифрування для вищезгаданих алгоритмів.

app/views/labs/labs/lab_3/_caesars.html.haml
%form#caesars_form{method: 'post', action: caesars_ciphers_path}
  %h5= t('lab3.caesars')
  .form-row
    .form-group.col-12
      %textarea#caesars_text.form-control{:required => true, :name => 'text', :rows => 5, :placeholder => t('lab3.form.text')}
        Расшифровывание – процесс нормального применения криптографического преобразования шифрованного текста в открытый.
  .form-row
    .form-group.col-md-6
      %input#caesars_offset.form-control{:required => true, :name => 'offset', :placeholder => t('lab3.form.offset'), :type => 'number', :value => 8}
    .form-group.col-md-6
      .form-check.form-check-inline
        %input#caesars_encode.form-check-input{:checked => true, :name => "encode", :type => "radio", :value => '1'}/
        %label.form-check-label{:for => "caesars_encode"}= t('lab3.form.encode')
      .form-check.form-check-inline
        %input#caesars_decode.form-check-input{:name => "encode", :type => "radio", :value => '0'}/
        %label.form-check-label{:for => "caesars_decode"}= t('lab3.form.decode')
  .form-group
    %button.btn.btn-primary.mb-2#caesars{:type => "submit"}= t('lab3.form.submit')
  .card
    .card-header
      = t('lab3.form.result')
    .card-body#caesar_result
      = t('lab3.form.request')

app/views/labs/labs/lab_3/_tabs.html.haml
%ul#pills-tab.nav.nav-pills.mb-3{:role => "tablist"}
  %li.nav-item
    %a#pills-caesar-res-tab.nav-link.active{"aria-controls" => "pills-home", "aria-selected" => "true", "data-toggle" => "pill", :href => "#pills-caesar-res", :role => "tab"}= t('lab3.caesars')
  %li.nav-item
    %a#pills-xor-res-tab.nav-link{"aria-controls" => "pills-profile", "aria-selected" => "false", "data-toggle" => "pill", :href => "#pills-xor-res", :role => "tab"}= t('lab3.xor')
#pills-tabContent.tab-content
  #pills-caesar-res.tab-pane.fade.show.active{"aria-labelledby" => "pills-caesar-res-tab", :role => "tabpanel"}
    = render 'labs/labs/lab_3/caesars'
  #pills-xor-res.tab-pane.fade{"aria-labelledby" => "pills-xor-res-tab", :role => "tabpanel"}
    = render 'labs/labs/lab_3/xor'

app/views/labs/shared/_heading.html.haml
.heading.mt-4#start
  %h5.text-center= @lab.title
.heading.mt-4
  %h5.text-center= @lab.topic
.sub-heading.mt-4
  %p.text-left
    %strong= t("activerecord.attributes.lab.goal") + ':'
    = @lab.goal
  %p.text-left
    %strong= t("activerecord.attributes.lab.task") + ':'
    = @lab.task

app/views/labs/show.html.haml
- provide(:title, @lab.title)
.row
  .col-md-4.col-sm-12
    = render "labs/shared/aside"
  .col-md-8.col-sm-12
    - if @lab.asset_name.present?
      .alert.alert-warning.alert-dismissible.mt-4.fade.show{:role => "alert"}
        = link_to download_lab_path(@lab), target: '_blank', class: 'alert-link' do
          = fa_icon 'download'
          = t('shared.download')
          звіт на диск
        %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
          %span{"aria-hidden" => "true"} ×
    = render 'labs/shared/heading'
    = render "labs/labs/#{@lab.partial_name}"

app/views/shared/_lab_list.html.haml
.list-group.mt-4
  = link_to root_path, class: "list-group-item list-group-item-action flex-column align-items-start #{active_class?(root_path)}" do
    .d-flex.w-100.justify-content-between
      %h5.mb-1= t('nav.title')
      %small
    %div
  - @labs.each do |l|
    = link_to lab_path(l), class: "list-group-item list-group-item-action flex-column align-items-start #{active_class?(lab_path(l))}" do
      .d-flex.w-100.justify-content-between
        %h5.mb-1= l.title
      %p.mb-1= l.topic
      %small.text-muted= t('activerecord.updated_in_words', time_in_words: time_ago_in_words(l.updated_at))

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-expand-md.navbar-dark.bg-dark
  = link_to root_path, class: 'navbar-brand' do
    = fa_icon 'leanpub'  
  %button.navbar-toggler{"aria-controls" => "navbarsExampleDefault", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarsExampleDefault", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarsExampleDefault.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item{ class: active_class?(root_path) }
        = link_to root_path, class: 'nav-link' do
          = fa_icon 'home'
          = t('link.home')
          %span.sr-only (current)
      %li.nav-item.dropdown
        %a#dropdown01.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown"}
          = fa_icon 'flask'
          = t('link.summary')
        .dropdown-menu{"aria-labelledby" => "dropdown01"}
          - if @labs.any?
            - @labs.each do |l|
              = link_to l.title, lab_path(l), class: "dropdown-item #{active_class?(lab_path(l))}"
          - else
            %a.dropdown-item.disabled= t('link.no_labs')
    %ul.navbar-nav.my-2.my-md-0.mr-md-3
      - if logged_in?
        %li.nav-item
          = link_to '#', class: 'nav-link' do
            = fa_icon 'user'
            = current_user.name
        %li.nav-item
          = link_to sessions_path, method: :delete, class: 'nav-link' do
            = fa_icon 'sign-out'
            = t('link.sign_out')
      - else
        %li.nav-item{ class: active_class?(new_session_path) }
          = link_to new_session_path, class: 'nav-link' do
            = fa_icon 'sign-in'
            = t('link.sign_in')
        %li.nav-item{ class: active_class?(new_user_path) }
          = link_to new_user_path, class: 'nav-link' do
            = fa_icon 'user-plus'
            = t('link.sign_up')

app/views/shared/_title.html.haml
.alert.alert-warning.alert-dismissible.mt-4.fade.show{:role => "alert"}
  = link_to title_doc_path, class: 'alert-link' do
    = fa_icon 'download'
    = t('shared.download')
    документ на диск
  %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
    %span{"aria-hidden" => "true"} ×
.heading.mt-4
  %h4.text-center МІНІСТЕРСТВО ОСВІТИ І НАУКИ УКРАЇНИ
  %h4.text-center ЧЕРКАСЬКИЙ НАЦІОНАЛЬНИЙ УНІВЕРСИТЕТ
  %h4.text-center  імені БОГДАНА ХМЕЛЬНИЦЬКОГО
.sub-heading.mt-4
  %h5.text-center Факультет обчислювальної техніки, інтелектуальних та управляючих систем
.sub-heading.mt-4
  %h5.text-center Кафедра програмного забезпечення автоматизованих систем
.title.mt-5.pt-5
  %h2.text-center Журнал звітів з лабораторних робіт
  %h2.text-center з дисципліни 'Безпека програм та даних'
.row.mt-5.pt-5.font-weight-bold
  .col-6.text-left
    %p Перевірив:
    %p доц. Супруненко О.О.
  .col-6.text-right
    %p Виконав:
    %p студент Бабін М. Ф.
    %p група КЕ-15
.row.mt-5.pt-5.font-weight-bold
  .col-12.text-center
    Черкаси  2018